config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :webhooks

  get 'dashboard/timeline'

  devise_for :users, controllers: { sessions: 'sessions' }
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # get '/', to: redirect('/', status: 302)

  get '/users/oauth/callback', to: 'users#callback'
  root 'credit_cases#index'
  get 'settings/webhooks', to: 'webhooks#index'
  resources :credit_cases

  # scope ':administration_id' do
  get '/', to: 'dashboard#timeline', as: :administration
  get 'search', to: 'search#search'
  localized do
    resources :invoices do
      resources :notes
    end
    resources :companies
    resources :credit_cases
    get 'settings', to: 'users#settings'
  end
  # end

  namespace :api do
    namespace :v1 do
      resources :credit_cases
      resources :invoices
      get '/me' => "credentials#me"
    end
  end
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  content    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  invoice_id :integer
#

class Note < ActiveRecord::Base
	belongs_to :invoice
	scope :desc, -> { order(created_at: :desc)}
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:content, :user_id, :invoice_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.slim
= form_for @note do |f|
  - if @note.errors.any?
    #error_explanation
      h2 = "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      ul
        - @note.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions = f.submit 'Save'

app/views/notes/_note.html.slim
li id="note_#{note.id}"
	= note.content
	= link_to 'Verwijder', note, method: :delete, remote: true

app/views/notes/create.js.erb
$('form.new_note').find('#note_content').val('')
$('.invoice-notes').prepend("<%= j render(partial: @note) %>");

app/views/notes/destroy.js.erb
$("#note_<%= @note.id %>").fadeOut();

app/views/notes/edit.html.slim
h1 Editing note

== render 'form'

= link_to 'Show', @note
'|
= link_to 'Back', notes_path

app/views/notes/index.html.slim
h1 Listing notes

table
  thead
    tr
      th Content
      th User
      th
      th
      th

  tbody
    - @notes.each do |note|
      tr
        td = note.content
        td = note.user_id
        td = link_to 'Show', note
        td = link_to 'Edit', edit_note_path(note)
        td = link_to 'Destroy', note, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Note', new_note_path

app/views/notes/new.html.slim
h1 New note

== render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.slim
p#notice = notice

p
  strong Content:
  = @note.content
p
  strong User:
  = @note.user_id

= link_to 'Edit', edit_note_path(@note)
'|
= link_to 'Back', notes_path