config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :webhooks

  get 'dashboard/timeline'

  devise_for :users, controllers: { sessions: 'sessions' }
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # get '/', to: redirect('/', status: 302)

  get '/users/oauth/callback', to: 'users#callback'
  root 'credit_cases#index'
  get 'settings/webhooks', to: 'webhooks#index'
  resources :credit_cases

  # scope ':administration_id' do
  get '/', to: 'dashboard#timeline', as: :administration
  get 'search', to: 'search#search'
  localized do
    resources :invoices do
      resources :notes
    end
    resources :companies
    resources :credit_cases
    get 'settings', to: 'users#settings'
  end
  # end

  namespace :api do
    namespace :v1 do
      resources :credit_cases
      resources :invoices
      get '/me' => "credentials#me"
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  name                   :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :credit_cases
	has_many :invoices
end

app/controllers/api/v1/users_controller.rb
module Api::V1
	class UsersController < BaseController
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def callback
    raise "#{params}"
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def settings
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions = f.submit 'Save'

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
      th Email
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/settings.html.slim
.alert.alert--notice
  button.close
    = iconic_tag('circle-x')
  .spinner Laden ..
  p.alert__description 
    | Bezig met het uitvoeren van een importeertaak. 
    = link_to 'Klik hier', '#', class: 'alert__link'
    |  voor meer details.
.panel.panel--medium.panel--default
  header
    .header__title 
      h2 Instellingen

  section
    .hide
      h3 Adresgegevens
      strong Payt BV
      br
      strong Ubbo Emmiussingel 21
      br
      strong 9035 BZ Groningen
      br
      br
      strong NL59 RABO 03255 39 529 tnv. M. Kingma

    ul.panel-list
      li.header Administratie instellingen
      li
        .options
          .switch
            input id="cmn-toggle-1" class="cmn-toggle cmn-toggle-round-flat" type="checkbox"
            label for="cmn-toggle-1"   
        .service
          h3 Vakantieknop
          p Pauzeer alle facturen en zaken
      li
        .options
          .switch
            input id="cmn-toggle-2" class="cmn-toggle cmn-toggle-round-flat" type="checkbox" checked="checked"
            label for="cmn-toggle-2"      
        h3 iDEAL betalingen
        p 
          | Activeer iDEAL betalingen 
          span.small
            | (Geactiveerd op 23 febr 2014)
      li
        .options
          .switch
            input id="cmn-toggle-3" class="cmn-toggle cmn-toggle-round-flat" type="checkbox" checked="checked"
            label for="cmn-toggle-3"      
        h3 Betalingsregeling
        p Debiteur mag voorstel voor betalingsregeling doen
      li.header Admin instellingen
      li
        .options
          .switch
            input id="cmn-toggle-4" class="cmn-toggle cmn-toggle-round-flat" type="checkbox"
            label for="cmn-toggle-4"      
        h3 Briefpapier
        p Briefhoofd aan facturen toevoegen
  

.panel.panel--small.panel--list
  section
    ul.settings.panel-list
      li.active = link_to 'Administraties', '#'
      li = link_to 'Webhooks', webhooks_path
      li = link_to 'Deurwaarder', '#'
      li = link_to 'Gebruikers', '#'
      li = link_to 'Flows', '#'

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path