config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :webhooks

  get 'dashboard/timeline'

  devise_for :users, controllers: { sessions: 'sessions' }
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # get '/', to: redirect('/', status: 302)

  get '/users/oauth/callback', to: 'users#callback'
  root 'credit_cases#index'
  get 'settings/webhooks', to: 'webhooks#index'
  resources :credit_cases

  # scope ':administration_id' do
  get '/', to: 'dashboard#timeline', as: :administration
  get 'search', to: 'search#search'
  localized do
    resources :invoices do
      resources :notes
    end
    resources :companies
    resources :credit_cases
    get 'settings', to: 'users#settings'
  end
  # end

  namespace :api do
    namespace :v1 do
      resources :credit_cases
      resources :invoices
      get '/me' => "credentials#me"
    end
  end
end

app/models/webhook.rb
# == Schema Information
#
# Table name: webhooks
#
#  id          :integer          not null, primary key
#  description :string
#  url         :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Webhook < ActiveRecord::Base
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  before_action :set_webhook, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: :index

  # GET /webhooks
  # GET /webhooks.json
  def index
    @webhooks = Webhook.all
    render json: @webhooks
  end

  # GET /webhooks/1
  # GET /webhooks/1.json
  def show
  end

  # GET /webhooks/new
  def new
    @webhook = Webhook.new
  end

  # GET /webhooks/1/edit
  def edit
  end

  # POST /webhooks
  # POST /webhooks.json
  def create
    @webhook = Webhook.new(webhook_params)

    respond_to do |format|
      if @webhook.save
        format.html { redirect_to @webhook, notice: 'Webhook was successfully created.' }
        format.json { render :show, status: :created, location: @webhook }
      else
        format.html { render :new }
        format.json { render json: @webhook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webhooks/1
  # PATCH/PUT /webhooks/1.json
  def update
    respond_to do |format|
      if @webhook.update(webhook_params)
        format.html { redirect_to @webhook, notice: 'Webhook was successfully updated.' }
        format.json { render :show, status: :ok, location: @webhook }
      else
        format.html { render :edit }
        format.json { render json: @webhook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webhooks/1
  # DELETE /webhooks/1.json
  def destroy
    @webhook.destroy
    respond_to do |format|
      format.html { redirect_to webhooks_url, notice: 'Webhook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webhook
      @webhook = Webhook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def webhook_params
      params.require(:webhook).permit(:description, :url)
    end
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/webhooks/_checkout.html.erb
<form action="/charge" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_ZJPXciwIutmczeLdKcQ49CFU"
    data-image="https://assets.moneybird.com/mbrs/assets/moneybird@2x.png"
    data-name="Mathijs Kingma"
    data-description="2 widgets"
    data-currency="eur"
    data-amount="2000">
  </script>
</form>

app/views/webhooks/_form.html.slim
= form_for @webhook do |f|
  - if @webhook.errors.any?
    #error_explanation
      h2 = "#{pluralize(@webhook.errors.count, "error")} prohibited this webhook from being saved:"
      ul
        - @webhook.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :url
    = f.text_field :url
  .actions = f.submit

app/views/webhooks/_webhook.html.slim
li
  h3
    = link_to webhook.description, '#'

app/views/webhooks/edit.html.slim
h1 Editing webhook

== render 'form'

= link_to 'Show', @webhook
'|
= link_to 'Back', webhooks_path

app/views/webhooks/index.html.slim
.alert.alert--notice
  button.close
  p.alert__description 

.panel.panel--medium.panel--default
  header
    .header__title 
      h2 Webhooks

  section
    .hide
      h3 Adresgegevens
      strong Payt BV
      br
      strong Ubbo Emmiussingel 21
      br
      strong 9035 BZ Groningen
      br
      br
      strong NL59 RABO 03255 39 529 tnv. M. Kingma

    ul.panel-list
      = render @webhooks

.panel.panel--small.panel--list
  section
    ul.settings.panel-list
      li = link_to 'Administraties', settings_path
      li.active = link_to 'Webhooks', '#'
      li = link_to 'Deurwaarder', '#'
      li = link_to 'Gebruikers', '#'
      li = link_to 'Flows', '#'

app/views/webhooks/new.html.slim
h1 New webhook

== render 'form'

= link_to 'Back', webhooks_path

app/views/webhooks/show.html.slim
p#notice = notice

p
  strong Description:
  = @webhook.description
p
  strong Url:
  = @webhook.url

= link_to 'Edit', edit_webhook_path(@webhook)
'|
= link_to 'Back', webhooks_path