config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :webhooks

  get 'dashboard/timeline'

  devise_for :users, controllers: { sessions: 'sessions' }
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  # get '/', to: redirect('/', status: 302)

  get '/users/oauth/callback', to: 'users#callback'
  root 'credit_cases#index'
  get 'settings/webhooks', to: 'webhooks#index'
  resources :credit_cases

  # scope ':administration_id' do
  get '/', to: 'dashboard#timeline', as: :administration
  get 'search', to: 'search#search'
  localized do
    resources :invoices do
      resources :notes
    end
    resources :companies
    resources :credit_cases
    get 'settings', to: 'users#settings'
  end
  # end

  namespace :api do
    namespace :v1 do
      resources :credit_cases
      resources :invoices
      get '/me' => "credentials#me"
    end
  end
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Company < ActiveRecord::Base
	has_many :administrations
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @companies = Company.all
    respond_with(@companies)
  end

  def show
    respond_with(@company)
  end

  def new
    @company = Company.new
    respond_with(@company)
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.save
    respond_with(@company)
  end

  def update
    @company.update(company_params)
    respond_with(@company)
  end

  def destroy
    @company.destroy
    respond_with(@company)
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.slim
= form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      h2 = "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      ul
        - @company.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/companies/edit.html.slim
h1 Editing company

== render 'form'

= link_to 'Show', @company
'|
= link_to 'Back', companies_path

app/views/companies/index.html.slim
h1 Listing companies

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @companies.each do |company|
      tr
        td = company.name
        td = link_to 'Show', company
        td = link_to 'Edit', edit_company_path(company)
        td = link_to 'Destroy', company_path(company), data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Company', new_company_path

app/views/companies/new.html.slim
h1 New company

== render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.slim
p#notice = notice

p
  strong Name:
  = @company.name

= render @company.administrations